import type { Metadata } from "next";
import "../styles/globals.css";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import type { AppProps } from "next/app";


export const metadata: Metadata = {
	title: "NextBud Home",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
